### ISSUE TITLE
Feature Request: Ability to choose timezone

### ISSUE THREAD

**Issue by killergerbah** [taximanli/kotobade-asobou#12]
**Is your feature request related to a problem? Please describe.**
I'm an American playing this game with people in various timezones, including some people living in Japan. Since the timezones are so far apart, we often can't share our results with each other for the same game until the people living in earlier timezones have woken up the next day. It would be great if we could pick a timezone to play the game in so that we can play the same day without having to worry about timezone.

**Describe the solution you'd like**
Ideally, a way to choose timezone from the settings. It could be an hour offset from GMT or UTC, or a list of regions of the world.

**Describe alternatives you've considered**
I've forked the repo and made a change to lock the timezone to JST in my own branch. At a later time I could investigate making a more complete change for this issue and submitting it as PR to this repo.

**Comment by taximanli** [comment]
That's a very good feedback! At this stage I'm leaning towards using JST as the timezone for all players around the world but happy to consider other options if the other options work better.

**Comment by killergerbah** [comment]
I certainly wouldn't mind that. I can only see some players maybe being surprised when the change first rolls out but I imagine that people would just get used to it.

**Comment by briantist** [comment]
I think an option to lock it to an arbitrary timezone is preferable to locking the game to a specific zone for all players. Certainly there are players all over the world who only play with people in their own timezone, and others who play across zones, so I feel the flexibility is best.

Personally.. I don't know what I'd pick either way, I play with people in my own timezone and those who are in JST, so tough choice for me 😅

**Comment by taximanli** [comment]
@killergerbah @briantist I've created [branch-choose-timezone](https://github.com/taximanli/kotobade-asobou/tree/branch-choose-timezone) for adding the ability to choose timezone.

I added the time zone selection dropdown in Settings Modal, with the help of npm package [react-timezone-select](https://www.npmjs.com/package/react-timezone-select)), and managed to get the selected timezone offset to be used in 
`src\lib\words.ts`

`const timezoneOffset = getStoredTimezoneOffset()`
e.g. timezoneOffset = 9 when "Tokyo" is selected, = 11 for "Sydney", = 0 for "London", -4 for "New York", -10 for "Hawaii"

However I can't quite get a hang of the calculation in `src\lib\words.ts` , to make sure the daily word is changed at midnight of the chosen time zone and the count down clock is showing the correct remaining time until the next word.
Do you have any idea how the calculations should be?

**Comment by briantist** [comment]
@taximanli I'm taking a look, but would be helpful to know what problem you're seeing with the current calculation, and if there is a way I can load the version of the game from that branch. I'd be happy to take a closer look with that and see if I can find anything.

One thing I'll recommend just from looking over 0ab892745159a9bce4e59795574e484591a6ea58 is to store the chosen time zone itself (by name or whatever) and not store the offset, because even though the library takes into account DST, that should mean that the offset returned will change depending on DST in the chosen zone.

I think that means that if you store the offset in local storage, and retrieve that, it will be wrong the next time DST occurs, unless the user selects their time zone again (or maybe selects another and then goes back to theirs, whatever it takes to hit the `set*` function again that stores the offset). So I _think_ it'd be better to get the offset on retrieval from local storage instead, as in, every time you're going to use it (and same goes for `Intl.DateTimeFormat().resolvedOptions().timeZone` as a default).

I am not a frontend dev and don't really know TS, so I may be wrong and maybe you already accounted for that.

Either way, it's probably not related to any current calculation issue you're seeing, just mentioning.

**Comment by killergerbah** [comment]
Hi, 
For reference this is what I did to lock the game to JST:
https://github.com/killergerbah/kotobade-asobou/commit/94282f9880379ad777602aa19ba5d77a5f39476a

So I believe it should be simple enough to calculate the correct epoch string. Then the only thing to watch out for is if the user selects a timezone that makes them go back in time, that it's not possible for them to play the same word twice (but maybe that's already taken care of).

I see some possibly nicer methods here:
https://stackoverflow.com/questions/15141762/how-to-initialize-a-javascript-date-to-a-particular-time-zone#:~:text=JavaScript's%20Date%20object%20tracks%20time,time%20in%20other%20time%20zones.

**Comment by taximanli** [comment]
@briantist @killergerbah Thanks the pointers and suggestions from both of you. I believe I've got the calculations right now. The latest changes are now committed to [branch-choose-timezone](https://github.com/taximanli/kotobade-asobou/tree/branch-choose-timezone). It doesn't store timezone offset but the offset is calculated from the stored timezone name (America/New York, Europe/Paris, Asia/Tokyo). And players can only switch timezone at the start of the game. The timezone is locked in once the game starts. If possible, I wonder if you have time to help test the timezone feature?

Couple of commands for pulling the code and run it.
`git checkout branch-choose-timezone`
`npm install`
`npm run start`

**Comment by killergerbah** [comment]
@taximanli 
I tested switching timezones back and forth while changing my system clock. I didn't see any errors with selecting the correct word of the day. I only noticed a visual bug with the "time until next word" timer. It seems to be broken for me even when starting from a clean slate (via incognito mode).
![スクリーンショット 2022-03-20 午前9 59 12](https://user-images.githubusercontent.com/2254858/159173747-121bac08-795f-4b2e-b6f3-a07ab8f36b02.png)

**Comment by taximanli** [comment]
Thanks for testing! I've made changes to `word.ts` file in [branch-choose-timezone](https://github.com/taximanli/kotobade-asobou/tree/branch-choose-timezone) and both the game # and countdown seem to be correct now. If you could pull the latest and help do a quick check on your side, it would be great!

**Comment by briantist** [comment]
thanks for these changes @taximanli  ! I'm sorry I didn't have a chance to try it out locally, I should be able to check it out in the next day or two if @killergerbah doesn't get to it first.

**Comment by killergerbah** [comment]
@taximanli
The timer seems fine now but I also noticed that when you start with a completely fresh state sometimes the app doesn't load. I see this error in the logs:
```
Uncaught ReferenceError: Cannot access 'setWordOfDay' before initialization
    at Module.setWordOfDay (bundle.js:6805:61)
    at setStoredTimezone (bundle.js:6296:42)
    at getStoredTimezone (bundle.js:6303:5)
    at getWordOfDay (bundle.js:6892:84)
    at Module../src/lib/words.ts (bundle.js:6917:5)
    at Module.options.factory (bundle.js:82501:31)
    at __webpack_require__ (bundle.js:81946:33)
    at fn (bundle.js:82172:21)
    at Module../src/lib/statuses.ts (bundle.js:6604:64)
    at Module.options.factory (bundle.js:82501:31)
```

**Comment by taximanli** [comment]
Thanks for raising this error to me! I've fixed this Uncaught ReferenceError for setWordOfDay. And I also updated the title of the Statistics pop-up to show the correct date based on the selected timezone. e.g.

Game #58 on March 22, 2022 (selected timezone is Sydney/Australia)
Game #57 on March 21, 2022 (selected timezone is Hawaii/United States)

I think this timezone feature is ready to be live very soon.

**Comment by taximanli** [comment]
The new feature "Set timezone" is now live. Refresh browser to see the new feature in Settings.
